# Setup
title:               Hana's Portfolio Site
tagline:              Hana's Portfolio Site
description:         My portfolio site for artistic projects
url:                 http://hanayoyo.github.io
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hana Dampf
  url:               
  email:            

# Gems
plugins:
  - jekyll-paginate

# Custom vars


#Github
repo: hanayoyo.github.io
